### ISSUE TITLE
Konfiguracja Travis

### ISSUE THREAD

**Issue by Borrubasz** [jedrzejlisiak/JSON-tools#2]

**Comment by mprzypasniak99** [comment]
Jędrzej skonfigurował Travisa, projekt się buduje. Zamykam

**Comment by Luber90** [comment]
Trzeba zrobić użytecznego poma XD

**Comment by jedrzejlisiak** [comment]
Wygląda na to, że Sprint 1 wymaga od nas tego co udało nam się już uczynić dla konfiguracji Travisa.
Pom działa tak jak powinien.  Zamykam!
