### ISSUE TITLE
Obsługa 1 pustego pliku – wszystkie linie jako różnica

### ISSUE THREAD

**Issue by Luber90** [jedrzejlisiak/JSON-tools#4]

**Comment by Wafellini** [comment]
Podanie jednego pustego pliku daje na wyjściu informację o tym że jeden plik jest pusty.
Zaznaczać jako zrobione?

**Comment by Luber90** [comment]
Powinno chyba pokazywać, że jest różnica i zwracać cały plik w jednej kolumnie a w drugiej nic
